import uuid
from datetime import datetime

from app.models.tag import Tag, TagCategory, TagStatus


SYSTEM_TAGS = [
    # PROGRAMMING (30 tags)
    {"name": "Python", "slug": "python", "category": TagCategory.PROGRAMMING, "description": "Python programming language"},
    {"name": "JavaScript", "slug": "javascript", "category": TagCategory.PROGRAMMING, "description": "JavaScript programming language"},
    {"name": "TypeScript", "slug": "typescript", "category": TagCategory.PROGRAMMING, "description": "TypeScript programming language"},
    {"name": "Java", "slug": "java", "category": TagCategory.PROGRAMMING, "description": "Java programming language"},
    {"name": "C++", "slug": "cpp", "category": TagCategory.PROGRAMMING, "description": "C++ programming language"},
    {"name": "C#", "slug": "csharp", "category": TagCategory.PROGRAMMING, "description": "C# programming language"},
    {"name": "Go", "slug": "go", "category": TagCategory.PROGRAMMING, "description": "Go programming language"},
    {"name": "Rust", "slug": "rust", "category": TagCategory.PROGRAMMING, "description": "Rust programming language"},
    {"name": "PHP", "slug": "php", "category": TagCategory.PROGRAMMING, "description": "PHP programming language"},
    {"name": "Ruby", "slug": "ruby", "category": TagCategory.PROGRAMMING, "description": "Ruby programming language"},
    {"name": "Swift", "slug": "swift", "category": TagCategory.PROGRAMMING, "description": "Swift programming language"},
    {"name": "Kotlin", "slug": "kotlin", "category": TagCategory.PROGRAMMING, "description": "Kotlin programming language"},
    {"name": "Scala", "slug": "scala", "category": TagCategory.PROGRAMMING, "description": "Scala programming language"},
    {"name": "R", "slug": "r", "category": TagCategory.PROGRAMMING, "description": "R programming language for statistics"},
    {"name": "MATLAB", "slug": "matlab", "category": TagCategory.PROGRAMMING, "description": "MATLAB programming environment"},
    {"name": "SQL", "slug": "sql", "category": TagCategory.PROGRAMMING, "description": "Structured Query Language"},
    {"name": "HTML", "slug": "html", "category": TagCategory.PROGRAMMING, "description": "HyperText Markup Language"},
    {"name": "CSS", "slug": "css", "category": TagCategory.PROGRAMMING, "description": "Cascading Style Sheets"},
    {"name": "Dart", "slug": "dart", "category": TagCategory.PROGRAMMING, "description": "Dart programming language"},
    {"name": "Elixir", "slug": "elixir", "category": TagCategory.PROGRAMMING, "description": "Elixir programming language"},
    {"name": "Haskell", "slug": "haskell", "category": TagCategory.PROGRAMMING, "description": "Haskell functional programming language"},
    {"name": "Lua", "slug": "lua", "category": TagCategory.PROGRAMMING, "description": "Lua scripting language"},
    {"name": "Perl", "slug": "perl", "category": TagCategory.PROGRAMMING, "description": "Perl programming language"},
    {"name": "Shell", "slug": "shell", "category": TagCategory.PROGRAMMING, "description": "Shell scripting"},
    {"name": "Assembly", "slug": "assembly", "category": TagCategory.PROGRAMMING, "description": "Assembly language"},
    {"name": "COBOL", "slug": "cobol", "category": TagCategory.PROGRAMMING, "description": "COBOL programming language"},
    {"name": "Fortran", "slug": "fortran", "category": TagCategory.PROGRAMMING, "description": "Fortran programming language"},
    {"name": "Clojure", "slug": "clojure", "category": TagCategory.PROGRAMMING, "description": "Clojure programming language"},
    {"name": "F#", "slug": "fsharp", "category": TagCategory.PROGRAMMING, "description": "F# programming language"},
    {"name": "OCaml", "slug": "ocaml", "category": TagCategory.PROGRAMMING, "description": "OCaml programming language"},

    # FRAMEWORK (25 tags)
    {"name": "React", "slug": "react", "category": TagCategory.FRAMEWORK, "description": "React JavaScript library"},
    {"name": "Angular", "slug": "angular", "category": TagCategory.FRAMEWORK, "description": "Angular framework"},
    {"name": "Vue.js", "slug": "vuejs", "category": TagCategory.FRAMEWORK, "description": "Vue.js framework"},
    {"name": "Django", "slug": "django", "category": TagCategory.FRAMEWORK, "description": "Django web framework"},
    {"name": "Flask", "slug": "flask", "category": TagCategory.FRAMEWORK, "description": "Flask web framework"},
    {"name": "FastAPI", "slug": "fastapi", "category": TagCategory.FRAMEWORK, "description": "FastAPI web framework"},
    {"name": "Spring Boot", "slug": "spring-boot", "category": TagCategory.FRAMEWORK, "description": "Spring Boot framework"},
    {"name": "Express.js", "slug": "expressjs", "category": TagCategory.FRAMEWORK, "description": "Express.js web framework"},
    {"name": "Next.js", "slug": "nextjs", "category": TagCategory.FRAMEWORK, "description": "Next.js React framework"},
    {"name": "Nuxt.js", "slug": "nuxtjs", "category": TagCategory.FRAMEWORK, "description": "Nuxt.js Vue framework"},
    {"name": "Laravel", "slug": "laravel", "category": TagCategory.FRAMEWORK, "description": "Laravel PHP framework"},
    {"name": "Ruby on Rails", "slug": "rails", "category": TagCategory.FRAMEWORK, "description": "Ruby on Rails framework"},
    {"name": ".NET", "slug": "dotnet", "category": TagCategory.FRAMEWORK, "description": ".NET framework"},
    {"name": "ASP.NET", "slug": "aspnet", "category": TagCategory.FRAMEWORK, "description": "ASP.NET framework"},
    {"name": "Symfony", "slug": "symfony", "category": TagCategory.FRAMEWORK, "description": "Symfony PHP framework"},
    {"name": "CodeIgniter", "slug": "codeigniter", "category": TagCategory.FRAMEWORK, "description": "CodeIgniter PHP framework"},
    {"name": "Svelte", "slug": "svelte", "category": TagCategory.FRAMEWORK, "description": "Svelte framework"},
    {"name": "Flutter", "slug": "flutter", "category": TagCategory.FRAMEWORK, "description": "Flutter mobile framework"},
    {"name": "React Native", "slug": "react-native", "category": TagCategory.FRAMEWORK, "description": "React Native mobile framework"},
    {"name": "Unity", "slug": "unity", "category": TagCategory.FRAMEWORK, "description": "Unity game engine"},
    {"name": "Unreal Engine", "slug": "unreal-engine", "category": TagCategory.FRAMEWORK, "description": "Unreal Engine game engine"},
    {"name": "TensorFlow", "slug": "tensorflow", "category": TagCategory.FRAMEWORK, "description": "TensorFlow machine learning framework"},
    {"name": "PyTorch", "slug": "pytorch", "category": TagCategory.FRAMEWORK, "description": "PyTorch machine learning framework"},
    {"name": "Electron", "slug": "electron", "category": TagCategory.FRAMEWORK, "description": "Electron desktop framework"},
    {"name": "Ionic", "slug": "ionic", "category": TagCategory.FRAMEWORK, "description": "Ionic mobile framework"},

    # TOOL (30 tags)
    {"name": "Git", "slug": "git", "category": TagCategory.TOOL, "description": "Git version control system"},
    {"name": "Docker", "slug": "docker", "category": TagCategory.TOOL, "description": "Docker containerization platform"},
    {"name": "Kubernetes", "slug": "kubernetes", "category": TagCategory.TOOL, "description": "Kubernetes container orchestration"},
    {"name": "AWS", "slug": "aws", "category": TagCategory.TOOL, "description": "Amazon Web Services cloud platform"},
    {"name": "Google Cloud", "slug": "google-cloud", "category": TagCategory.TOOL, "description": "Google Cloud Platform"},
    {"name": "Azure", "slug": "azure", "category": TagCategory.TOOL, "description": "Microsoft Azure cloud platform"},
    {"name": "Jenkins", "slug": "jenkins", "category": TagCategory.TOOL, "description": "Jenkins automation server"},
    {"name": "GitHub Actions", "slug": "github-actions", "category": TagCategory.TOOL, "description": "GitHub Actions CI/CD"},
    {"name": "Terraform", "slug": "terraform", "category": TagCategory.TOOL, "description": "Terraform infrastructure as code"},
    {"name": "Ansible", "slug": "ansible", "category": TagCategory.TOOL, "description": "Ansible automation tool"},
    {"name": "Jira", "slug": "jira", "category": TagCategory.TOOL, "description": "Jira project management"},
    {"name": "Slack", "slug": "slack", "category": TagCategory.TOOL, "description": "Slack communication platform"},
    {"name": "Discord", "slug": "discord", "category": TagCategory.TOOL, "description": "Discord communication platform"},
    {"name": "Figma", "slug": "figma", "category": TagCategory.TOOL, "description": "Figma design tool"},
    {"name": "Photoshop", "slug": "photoshop", "category": TagCategory.TOOL, "description": "Adobe Photoshop"},
    {"name": "Illustrator", "slug": "illustrator", "category": TagCategory.TOOL, "description": "Adobe Illustrator"},
    {"name": "After Effects", "slug": "after-effects", "category": TagCategory.TOOL, "description": "Adobe After Effects"},
    {"name": "Premiere Pro", "slug": "premiere-pro", "category": TagCategory.TOOL, "description": "Adobe Premiere Pro"},
    {"name": "Blender", "slug": "blender", "category": TagCategory.TOOL, "description": "Blender 3D software"},
    {"name": "Maya", "slug": "maya", "category": TagCategory.TOOL, "description": "Autodesk Maya"},
    {"name": "3ds Max", "slug": "3ds-max", "category": TagCategory.TOOL, "description": "Autodesk 3ds Max"},
    {"name": "AutoCAD", "slug": "autocad", "category": TagCategory.TOOL, "description": "AutoCAD design software"},
    {"name": "Excel", "slug": "excel", "category": TagCategory.TOOL, "description": "Microsoft Excel"},
    {"name": "Tableau", "slug": "tableau", "category": TagCategory.TOOL, "description": "Tableau data visualization"},
    {"name": "Power BI", "slug": "power-bi", "category": TagCategory.TOOL, "description": "Microsoft Power BI"},
    {"name": "Postman", "slug": "postman", "category": TagCategory.TOOL, "description": "Postman API testing tool"},
    {"name": "VS Code", "slug": "vscode", "category": TagCategory.TOOL, "description": "Visual Studio Code editor"},
    {"name": "IntelliJ IDEA", "slug": "intellij", "category": TagCategory.TOOL, "description": "IntelliJ IDEA IDE"},
    {"name": "Notion", "slug": "notion", "category": TagCategory.TOOL, "description": "Notion workspace"},
    {"name": "Trello", "slug": "trello", "category": TagCategory.TOOL, "description": "Trello project management"},

    # GAME (25 tags)
    {"name": "League of Legends", "slug": "league-of-legends", "category": TagCategory.GAME, "description": "League of Legends MOBA game"},
    {"name": "Dota 2", "slug": "dota2", "category": TagCategory.GAME, "description": "Dota 2 MOBA game"},
    {"name": "Counter-Strike 2", "slug": "cs2", "category": TagCategory.GAME, "description": "Counter-Strike 2 FPS game"},
    {"name": "Valorant", "slug": "valorant", "category": TagCategory.GAME, "description": "Valorant tactical FPS"},
    {"name": "Overwatch 2", "slug": "overwatch2", "category": TagCategory.GAME, "description": "Overwatch 2 team shooter"},
    {"name": "World of Warcraft", "slug": "wow", "category": TagCategory.GAME, "description": "World of Warcraft MMORPG"},
    {"name": "Final Fantasy XIV", "slug": "ffxiv", "category": TagCategory.GAME, "description": "Final Fantasy XIV MMORPG"},
    {"name": "Minecraft", "slug": "minecraft", "category": TagCategory.GAME, "description": "Minecraft sandbox game"},
    {"name": "Among Us", "slug": "among-us", "category": TagCategory.GAME, "description": "Among Us social deduction game"},
    {"name": "Fall Guys", "slug": "fall-guys", "category": TagCategory.GAME, "description": "Fall Guys party game"},
    {"name": "Rocket League", "slug": "rocket-league", "category": TagCategory.GAME, "description": "Rocket League vehicular soccer"},
    {"name": "Fortnite", "slug": "fortnite", "category": TagCategory.GAME, "description": "Fortnite battle royale"},
    {"name": "Apex Legends", "slug": "apex-legends", "category": TagCategory.GAME, "description": "Apex Legends battle royale"},
    {"name": "Chess", "slug": "chess", "category": TagCategory.GAME, "description": "Chess board game"},
    {"name": "Poker", "slug": "poker", "category": TagCategory.GAME, "description": "Poker card game"},
    {"name": "Dungeons & Dragons", "slug": "dnd", "category": TagCategory.GAME, "description": "Dungeons & Dragons tabletop RPG"},
    {"name": "Magic: The Gathering", "slug": "mtg", "category": TagCategory.GAME, "description": "Magic: The Gathering card game"},
    {"name": "Hearthstone", "slug": "hearthstone", "category": TagCategory.GAME, "description": "Hearthstone digital card game"},
    {"name": "Genshin Impact", "slug": "genshin-impact", "category": TagCategory.GAME, "description": "Genshin Impact action RPG"},
    {"name": "Destiny 2", "slug": "destiny2", "category": TagCategory.GAME, "description": "Destiny 2 online FPS"},
    {"name": "Animal Crossing", "slug": "animal-crossing", "category": TagCategory.GAME, "description": "Animal Crossing life simulation"},
    {"name": "Stardew Valley", "slug": "stardew-valley", "category": TagCategory.GAME, "description": "Stardew Valley farming simulation"},
    {"name": "Terraria", "slug": "terraria", "category": TagCategory.GAME, "description": "Terraria sandbox adventure"},
    {"name": "Dead by Daylight", "slug": "dead-by-daylight", "category": TagCategory.GAME, "description": "Dead by Daylight asymmetric horror"},
    {"name": "Rainbow Six Siege", "slug": "r6-siege", "category": TagCategory.GAME, "description": "Rainbow Six Siege tactical shooter"},

    # GAME_GENRE (15 tags)
    {"name": "MOBA", "slug": "moba", "category": TagCategory.GAME_GENRE, "description": "Multiplayer Online Battle Arena"},
    {"name": "FPS", "slug": "fps", "category": TagCategory.GAME_GENRE, "description": "First Person Shooter"},
    {"name": "RPG", "slug": "rpg", "category": TagCategory.GAME_GENRE, "description": "Role Playing Game"},
    {"name": "MMORPG", "slug": "mmorpg", "category": TagCategory.GAME_GENRE, "description": "Massively Multiplayer Online RPG"},
    {"name": "Strategy", "slug": "strategy", "category": TagCategory.GAME_GENRE, "description": "Strategy games"},
    {"name": "Puzzle", "slug": "puzzle", "category": TagCategory.GAME_GENRE, "description": "Puzzle games"},
    {"name": "Racing", "slug": "racing", "category": TagCategory.GAME_GENRE, "description": "Racing games"},
    {"name": "Fighting", "slug": "fighting", "category": TagCategory.GAME_GENRE, "description": "Fighting games"},
    {"name": "Platform", "slug": "platform", "category": TagCategory.GAME_GENRE, "description": "Platform games"},
    {"name": "Simulation", "slug": "simulation", "category": TagCategory.GAME_GENRE, "description": "Simulation games"},
    {"name": "Sandbox", "slug": "sandbox", "category": TagCategory.GAME_GENRE, "description": "Sandbox games"},
    {"name": "Battle Royale", "slug": "battle-royale", "category": TagCategory.GAME_GENRE, "description": "Battle Royale games"},
    {"name": "Card Game", "slug": "card-game", "category": TagCategory.GAME_GENRE, "description": "Card games"},
    {"name": "Board Game", "slug": "board-game", "category": TagCategory.GAME_GENRE, "description": "Board games"},
    {"name": "Party Game", "slug": "party-game", "category": TagCategory.GAME_GENRE, "description": "Party games"},

    # ART (20 tags)
    {"name": "Drawing", "slug": "drawing", "category": TagCategory.ART, "description": "Drawing and sketching"},
    {"name": "Painting", "slug": "painting", "category": TagCategory.ART, "description": "Painting with various mediums"},
    {"name": "Digital Art", "slug": "digital-art", "category": TagCategory.ART, "description": "Digital artwork creation"},
    {"name": "Sculpture", "slug": "sculpture", "category": TagCategory.ART, "description": "3D sculpture art"},
    {"name": "Illustration", "slug": "illustration", "category": TagCategory.ART, "description": "Illustration art"},
    {"name": "Character Design", "slug": "character-design", "category": TagCategory.ART, "description": "Character design and concept art"},
    {"name": "Concept Art", "slug": "concept-art", "category": TagCategory.ART, "description": "Concept art creation"},
    {"name": "Animation", "slug": "animation", "category": TagCategory.ART, "description": "Animation and motion graphics"},
    {"name": "Pixel Art", "slug": "pixel-art", "category": TagCategory.ART, "description": "Pixel art creation"},
    {"name": "Watercolor", "slug": "watercolor", "category": TagCategory.ART, "description": "Watercolor painting"},
    {"name": "Oil Painting", "slug": "oil-painting", "category": TagCategory.ART, "description": "Oil painting"},
    {"name": "Acrylic Painting", "slug": "acrylic-painting", "category": TagCategory.ART, "description": "Acrylic painting"},
    {"name": "Pencil Art", "slug": "pencil-art", "category": TagCategory.ART, "description": "Pencil drawing and art"},
    {"name": "Ink Drawing", "slug": "ink-drawing", "category": TagCategory.ART, "description": "Ink drawing and illustration"},
    {"name": "Calligraphy", "slug": "calligraphy", "category": TagCategory.ART, "description": "Calligraphy and lettering"},
    {"name": "Graffiti", "slug": "graffiti", "category": TagCategory.ART, "description": "Graffiti and street art"},
    {"name": "Pottery", "slug": "pottery", "category": TagCategory.ART, "description": "Pottery and ceramics"},
    {"name": "Printmaking", "slug": "printmaking", "category": TagCategory.ART, "description": "Printmaking techniques"},
    {"name": "Mixed Media", "slug": "mixed-media", "category": TagCategory.ART, "description": "Mixed media art"},
    {"name": "Street Art", "slug": "street-art", "category": TagCategory.ART, "description": "Street art and murals"},

    # MUSIC (20 tags)
    {"name": "Guitar", "slug": "guitar", "category": TagCategory.MUSIC, "description": "Guitar playing and music"},
    {"name": "Piano", "slug": "piano", "category": TagCategory.MUSIC, "description": "Piano playing and music"},
    {"name": "Drums", "slug": "drums", "category": TagCategory.MUSIC, "description": "Drum playing and percussion"},
    {"name": "Violin", "slug": "violin", "category": TagCategory.MUSIC, "description": "Violin playing"},
    {"name": "Bass", "slug": "bass", "category": TagCategory.MUSIC, "description": "Bass guitar playing"},
    {"name": "Vocals", "slug": "vocals", "category": TagCategory.MUSIC, "description": "Singing and vocal performance"},
    {"name": "Music Production", "slug": "music-production", "category": TagCategory.MUSIC, "description": "Music production and recording"},
    {"name": "DJing", "slug": "djing", "category": TagCategory.MUSIC, "description": "DJ performance and mixing"},
    {"name": "Jazz", "slug": "jazz", "category": TagCategory.MUSIC, "description": "Jazz music"},
    {"name": "Rock", "slug": "rock", "category": TagCategory.MUSIC, "description": "Rock music"},
    {"name": "Pop", "slug": "pop", "category": TagCategory.MUSIC, "description": "Pop music"},
    {"name": "Electronic", "slug": "electronic", "category": TagCategory.MUSIC, "description": "Electronic music"},
    {"name": "Classical", "slug": "classical", "category": TagCategory.MUSIC, "description": "Classical music"},
    {"name": "Hip Hop", "slug": "hip-hop", "category": TagCategory.MUSIC, "description": "Hip hop music"},
    {"name": "R&B", "slug": "rnb", "category": TagCategory.MUSIC, "description": "R&B music"},
    {"name": "Country", "slug": "country", "category": TagCategory.MUSIC, "description": "Country music"},
    {"name": "Folk", "slug": "folk", "category": TagCategory.MUSIC, "description": "Folk music"},
    {"name": "Reggae", "slug": "reggae", "category": TagCategory.MUSIC, "description": "Reggae music"},
    {"name": "Blues", "slug": "blues", "category": TagCategory.MUSIC, "description": "Blues music"},
    {"name": "Metal", "slug": "metal", "category": TagCategory.MUSIC, "description": "Metal music"},

    # MEDIA (15 tags)
    {"name": "Photography", "slug": "photography", "category": TagCategory.MEDIA, "description": "Photography and photo editing"},
    {"name": "Video Editing", "slug": "video-editing", "category": TagCategory.MEDIA, "description": "Video editing and post-production"},
    {"name": "Streaming", "slug": "streaming", "category": TagCategory.MEDIA, "description": "Live streaming and content creation"},
    {"name": "Podcasting", "slug": "podcasting", "category": TagCategory.MEDIA, "description": "Podcast creation and production"},
    {"name": "YouTube", "slug": "youtube", "category": TagCategory.MEDIA, "description": "YouTube content creation"},
    {"name": "TikTok", "slug": "tiktok", "category": TagCategory.MEDIA, "description": "TikTok content creation"},
    {"name": "Instagram", "slug": "instagram", "category": TagCategory.MEDIA, "description": "Instagram content and social media"},
    {"name": "Blogging", "slug": "blogging", "category": TagCategory.MEDIA, "description": "Blog writing and content creation"},
    {"name": "Writing", "slug": "writing", "category": TagCategory.MEDIA, "description": "Creative and technical writing"},
    {"name": "Journalism", "slug": "journalism", "category": TagCategory.MEDIA, "description": "Journalism and news writing"},
    {"name": "Copywriting", "slug": "copywriting", "category": TagCategory.MEDIA, "description": "Marketing and advertising copy"},
    {"name": "Screenwriting", "slug": "screenwriting", "category": TagCategory.MEDIA, "description": "Screenwriting for film and TV"},
    {"name": "Documentary", "slug": "documentary", "category": TagCategory.MEDIA, "description": "Documentary filmmaking"},
    {"name": "Voice Acting", "slug": "voice-acting", "category": TagCategory.MEDIA, "description": "Voice acting and narration"},
    {"name": "Social Media", "slug": "social-media", "category": TagCategory.MEDIA, "description": "Social media management and marketing"},

    # SPORT (20 tags)
    {"name": "Basketball", "slug": "basketball", "category": TagCategory.SPORT, "description": "Basketball sport"},
    {"name": "Soccer", "slug": "soccer", "category": TagCategory.SPORT, "description": "Soccer/Football sport"},
    {"name": "Tennis", "slug": "tennis", "category": TagCategory.SPORT, "description": "Tennis sport"},
    {"name": "Baseball", "slug": "baseball", "category": TagCategory.SPORT, "description": "Baseball sport"},
    {"name": "American Football", "slug": "american-football", "category": TagCategory.SPORT, "description": "American Football sport"},
    {"name": "Volleyball", "slug": "volleyball", "category": TagCategory.SPORT, "description": "Volleyball sport"},
    {"name": "Swimming", "slug": "swimming", "category": TagCategory.SPORT, "description": "Swimming sport"},
    {"name": "Running", "slug": "running", "category": TagCategory.SPORT, "description": "Running and athletics"},
    {"name": "Cycling", "slug": "cycling", "category": TagCategory.SPORT, "description": "Cycling and biking"},
    {"name": "Golf", "slug": "golf", "category": TagCategory.SPORT, "description": "Golf sport"},
    {"name": "Badminton", "slug": "badminton", "category": TagCategory.SPORT, "description": "Badminton sport"},
    {"name": "Table Tennis", "slug": "table-tennis", "category": TagCategory.SPORT, "description": "Table tennis/ping pong"},
    {"name": "Hockey", "slug": "hockey", "category": TagCategory.SPORT, "description": "Hockey sport"},
    {"name": "Cricket", "slug": "cricket", "category": TagCategory.SPORT, "description": "Cricket sport"},
    {"name": "Rugby", "slug": "rugby", "category": TagCategory.SPORT, "description": "Rugby sport"},
    {"name": "Boxing", "slug": "boxing", "category": TagCategory.SPORT, "description": "Boxing sport"},
    {"name": "Martial Arts", "slug": "martial-arts", "category": TagCategory.SPORT, "description": "Martial arts and combat sports"},
    {"name": "Rock Climbing", "slug": "rock-climbing", "category": TagCategory.SPORT, "description": "Rock climbing and bouldering"},
    {"name": "Skiing", "slug": "skiing", "category": TagCategory.SPORT, "description": "Skiing and winter sports"},
    {"name": "Surfing", "slug": "surfing", "category": TagCategory.SPORT, "description": "Surfing and water sports"},

    # FITNESS (15 tags)
    {"name": "Weightlifting", "slug": "weightlifting", "category": TagCategory.FITNESS, "description": "Weightlifting and strength training"},
    {"name": "Yoga", "slug": "yoga", "category": TagCategory.FITNESS, "description": "Yoga practice and instruction"},
    {"name": "Pilates", "slug": "pilates", "category": TagCategory.FITNESS, "description": "Pilates exercise method"},
    {"name": "CrossFit", "slug": "crossfit", "category": TagCategory.FITNESS, "description": "CrossFit training methodology"},
    {"name": "Cardio", "slug": "cardio", "category": TagCategory.FITNESS, "description": "Cardiovascular exercise"},
    {"name": "Calisthenics", "slug": "calisthenics", "category": TagCategory.FITNESS, "description": "Bodyweight exercise training"},
    {"name": "Personal Training", "slug": "personal-training", "category": TagCategory.FITNESS, "description": "Personal fitness training"},
    {"name": "Nutrition", "slug": "nutrition", "category": TagCategory.FITNESS, "description": "Nutrition and diet planning"},
    {"name": "Bodybuilding", "slug": "bodybuilding", "category": TagCategory.FITNESS, "description": "Bodybuilding and physique development"},
    {"name": "Dance Fitness", "slug": "dance-fitness", "category": TagCategory.FITNESS, "description": "Dance-based fitness activities"},
    {"name": "Flexibility", "slug": "flexibility", "category": TagCategory.FITNESS, "description": "Flexibility and mobility training"},
    {"name": "HIIT", "slug": "hiit", "category": TagCategory.FITNESS, "description": "High-Intensity Interval Training"},
    {"name": "Meditation", "slug": "meditation", "category": TagCategory.FITNESS, "description": "Meditation and mindfulness practice"},
    {"name": "Stretching", "slug": "stretching", "category": TagCategory.FITNESS, "description": "Stretching and recovery"},
    {"name": "Functional Training", "slug": "functional-training", "category": TagCategory.FITNESS, "description": "Functional movement training"},

    # LANGUAGE (15 tags)
    {"name": "English", "slug": "english", "category": TagCategory.LANGUAGE, "description": "English language"},
    {"name": "Spanish", "slug": "spanish", "category": TagCategory.LANGUAGE, "description": "Spanish language"},
    {"name": "French", "slug": "french", "category": TagCategory.LANGUAGE, "description": "French language"},
    {"name": "German", "slug": "german", "category": TagCategory.LANGUAGE, "description": "German language"},
    {"name": "Italian", "slug": "italian", "category": TagCategory.LANGUAGE, "description": "Italian language"},
    {"name": "Portuguese", "slug": "portuguese", "category": TagCategory.LANGUAGE, "description": "Portuguese language"},
    {"name": "Mandarin", "slug": "mandarin", "category": TagCategory.LANGUAGE, "description": "Mandarin Chinese language"},
    {"name": "Japanese", "slug": "japanese", "category": TagCategory.LANGUAGE, "description": "Japanese language"},
    {"name": "Korean", "slug": "korean", "category": TagCategory.LANGUAGE, "description": "Korean language"},
    {"name": "Russian", "slug": "russian", "category": TagCategory.LANGUAGE, "description": "Russian language"},
    {"name": "Arabic", "slug": "arabic", "category": TagCategory.LANGUAGE, "description": "Arabic language"},
    {"name": "Hindi", "slug": "hindi", "category": TagCategory.LANGUAGE, "description": "Hindi language"},
    {"name": "Dutch", "slug": "dutch", "category": TagCategory.LANGUAGE, "description": "Dutch language"},
    {"name": "Swedish", "slug": "swedish", "category": TagCategory.LANGUAGE, "description": "Swedish language"},
    {"name": "Thai", "slug": "thai", "category": TagCategory.LANGUAGE, "description": "Thai language"},

    # SUBJECT (20 tags)
    {"name": "Mathematics", "slug": "mathematics", "category": TagCategory.SUBJECT, "description": "Mathematics and mathematical concepts"},
    {"name": "Physics", "slug": "physics", "category": TagCategory.SUBJECT, "description": "Physics and physical sciences"},
    {"name": "Chemistry", "slug": "chemistry", "category": TagCategory.SUBJECT, "description": "Chemistry and chemical sciences"},
    {"name": "Biology", "slug": "biology", "category": TagCategory.SUBJECT, "description": "Biology and life sciences"},
    {"name": "History", "slug": "history", "category": TagCategory.SUBJECT, "description": "History and historical studies"},
    {"name": "Psychology", "slug": "psychology", "category": TagCategory.SUBJECT, "description": "Psychology and behavioral sciences"},
    {"name": "Philosophy", "slug": "philosophy", "category": TagCategory.SUBJECT, "description": "Philosophy and philosophical thinking"},
    {"name": "Economics", "slug": "economics", "category": TagCategory.SUBJECT, "description": "Economics and economic theory"},
    {"name": "Political Science", "slug": "political-science", "category": TagCategory.SUBJECT, "description": "Political science and government"},
    {"name": "Sociology", "slug": "sociology", "category": TagCategory.SUBJECT, "description": "Sociology and social sciences"},
    {"name": "Literature", "slug": "literature", "category": TagCategory.SUBJECT, "description": "Literature and literary studies"},
    {"name": "Art History", "slug": "art-history", "category": TagCategory.SUBJECT, "description": "Art history and cultural studies"},
    {"name": "Geography", "slug": "geography", "category": TagCategory.SUBJECT, "description": "Geography and earth sciences"},
    {"name": "Astronomy", "slug": "astronomy", "category": TagCategory.SUBJECT, "description": "Astronomy and space sciences"},
    {"name": "Computer Science", "slug": "computer-science", "category": TagCategory.SUBJECT, "description": "Computer science and computational theory"},
    {"name": "Engineering", "slug": "engineering", "category": TagCategory.SUBJECT, "description": "Engineering and applied sciences"},
    {"name": "Medicine", "slug": "medicine", "category": TagCategory.SUBJECT, "description": "Medicine and healthcare"},
    {"name": "Law", "slug": "law", "category": TagCategory.SUBJECT, "description": "Law and legal studies"},
    {"name": "Business", "slug": "business", "category": TagCategory.SUBJECT, "description": "Business and management"},
    {"name": "Statistics", "slug": "statistics", "category": TagCategory.SUBJECT, "description": "Statistics and data analysis"},

    # SKILL (15 tags)
    {"name": "Leadership", "slug": "leadership", "category": TagCategory.SKILL, "description": "Leadership and management skills"},
    {"name": "Communication", "slug": "communication", "category": TagCategory.SKILL, "description": "Communication and interpersonal skills"},
    {"name": "Problem Solving", "slug": "problem-solving", "category": TagCategory.SKILL, "description": "Problem solving and analytical thinking"},
    {"name": "Teamwork", "slug": "teamwork", "category": TagCategory.SKILL, "description": "Teamwork and collaboration"},
    {"name": "Time Management", "slug": "time-management", "category": TagCategory.SKILL, "description": "Time management and productivity"},
    {"name": "Critical Thinking", "slug": "critical-thinking", "category": TagCategory.SKILL, "description": "Critical thinking and analysis"},
    {"name": "Creativity", "slug": "creativity", "category": TagCategory.SKILL, "description": "Creative thinking and innovation"},
    {"name": "Negotiation", "slug": "negotiation", "category": TagCategory.SKILL, "description": "Negotiation and persuasion"},
    {"name": "Public Speaking", "slug": "public-speaking", "category": TagCategory.SKILL, "description": "Public speaking and presentation"},
    {"name": "Project Management", "slug": "project-management", "category": TagCategory.SKILL, "description": "Project management and planning"},
    {"name": "Research", "slug": "research", "category": TagCategory.SKILL, "description": "Research and investigation skills"},
    {"name": "Teaching", "slug": "teaching", "category": TagCategory.SKILL, "description": "Teaching and mentoring"},
    {"name": "Mentoring", "slug": "mentoring", "category": TagCategory.SKILL, "description": "Mentoring and coaching"},
    {"name": "Organization", "slug": "organization", "category": TagCategory.SKILL, "description": "Organization and planning skills"},
    {"name": "Adaptability", "slug": "adaptability", "category": TagCategory.SKILL, "description": "Adaptability and flexibility"},

    # HOBBY (15 tags)
    {"name": "Cooking", "slug": "cooking", "category": TagCategory.HOBBY, "description": "Cooking and culinary arts"},
    {"name": "Baking", "slug": "baking", "category": TagCategory.HOBBY, "description": "Baking and pastry making"},
    {"name": "Reading", "slug": "reading", "category": TagCategory.HOBBY, "description": "Reading books and literature"},
    {"name": "Gardening", "slug": "gardening", "category": TagCategory.HOBBY, "description": "Gardening and plant cultivation"},
    {"name": "Board Games", "slug": "board-games", "category": TagCategory.HOBBY, "description": "Board games and tabletop gaming"},
    {"name": "Card Games", "slug": "card-games", "category": TagCategory.HOBBY, "description": "Card games and playing cards"},
    {"name": "Crafting", "slug": "crafting", "category": TagCategory.HOBBY, "description": "Arts and crafts activities"},
    {"name": "Knitting", "slug": "knitting", "category": TagCategory.HOBBY, "description": "Knitting and textile crafts"},
    {"name": "Woodworking", "slug": "woodworking", "category": TagCategory.HOBBY, "description": "Woodworking and carpentry"},
    {"name": "Collecting", "slug": "collecting", "category": TagCategory.HOBBY, "description": "Collecting items and memorabilia"},
    {"name": "Travel", "slug": "travel", "category": TagCategory.HOBBY, "description": "Travel and exploration"},
    {"name": "Hiking", "slug": "hiking", "category": TagCategory.HOBBY, "description": "Hiking and outdoor activities"},
    {"name": "Camping", "slug": "camping", "category": TagCategory.HOBBY, "description": "Camping and outdoor recreation"},
    {"name": "Fishing", "slug": "fishing", "category": TagCategory.HOBBY, "description": "Fishing and angling"},
    {"name": "Bird Watching", "slug": "bird-watching", "category": TagCategory.HOBBY, "description": "Bird watching and nature observation"},

    # LOCATION (10 tags)
    {"name": "Remote", "slug": "remote", "category": TagCategory.LOCATION, "description": "Remote/online activities"},
    {"name": "Local", "slug": "local", "category": TagCategory.LOCATION, "description": "Local in-person activities"},
    {"name": "North America", "slug": "north-america", "category": TagCategory.LOCATION, "description": "North America region"},
    {"name": "Europe", "slug": "europe", "category": TagCategory.LOCATION, "description": "Europe region"},
    {"name": "Asia", "slug": "asia", "category": TagCategory.LOCATION, "description": "Asia region"},
    {"name": "South America", "slug": "south-america", "category": TagCategory.LOCATION, "description": "South America region"},
    {"name": "Africa", "slug": "africa", "category": TagCategory.LOCATION, "description": "Africa region"},
    {"name": "Oceania", "slug": "oceania", "category": TagCategory.LOCATION, "description": "Oceania region"},
    {"name": "Urban", "slug": "urban", "category": TagCategory.LOCATION, "description": "Urban city environment"},
    {"name": "Outdoor", "slug": "outdoor", "category": TagCategory.LOCATION, "description": "Outdoor activities and venues"},

    # STYLE (10 tags)
    {"name": "Casual", "slug": "casual", "category": TagCategory.STYLE, "description": "Casual and relaxed approach"},
    {"name": "Competitive", "slug": "competitive", "category": TagCategory.STYLE, "description": "Competitive and serious approach"},
    {"name": "Beginner Friendly", "slug": "beginner-friendly", "category": TagCategory.STYLE, "description": "Welcoming to beginners"},
    {"name": "Advanced", "slug": "advanced", "category": TagCategory.STYLE, "description": "For experienced participants"},
    {"name": "Educational", "slug": "educational", "category": TagCategory.STYLE, "description": "Learning-focused approach"},
    {"name": "Social", "slug": "social", "category": TagCategory.STYLE, "description": "Socially-oriented activities"},
    {"name": "Professional", "slug": "professional", "category": TagCategory.STYLE, "description": "Professional development focused"},
    {"name": "Creative", "slug": "creative", "category": TagCategory.STYLE, "description": "Creative and artistic approach"},
    {"name": "Structured", "slug": "structured", "category": TagCategory.STYLE, "description": "Highly organized and structured"},
    {"name": "Flexible", "slug": "flexible", "category": TagCategory.STYLE, "description": "Flexible and adaptable approach"},
]


def create_system_tags(session):
    """Create system tags from the predefined list."""
    created_count = 0
    
    for tag_data in SYSTEM_TAGS:
        # Check if tag already exists by slug
        from app.crud.tag import get_tag_by_slug
        existing_tag = get_tag_by_slug(session=session, slug=tag_data["slug"])
        
        if not existing_tag:
            # Create new tag
            tag = Tag(
                id=uuid.uuid4(),
                name=tag_data["name"],
                slug=tag_data["slug"],
                category=tag_data["category"],
                description=tag_data["description"],
                status=TagStatus.SYSTEM,
                usage_count=0,
                created_at=datetime.utcnow(),
                updated_at=datetime.utcnow()
            )
            session.add(tag)
            created_count += 1
    
    session.commit()
    return created_count