"""trying to fix Item problem

Revision ID: 35b8dba80cd8
Revises: a9c6b78075cf
Create Date: 2025-08-31 19:24:58.324765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35b8dba80cd8'
down_revision = 'a9c6b78075cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
