"""Remove items from User

Revision ID: 5d18dbc8c7e9
Revises: f141eba18e94
Create Date: 2025-08-31 20:02:20.643998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d18dbc8c7e9'
down_revision = 'f141eba18e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
