"""add quest member model for quest membership tracking

Revision ID: 777a974b47b4
Revises: 978bd79d7643
Create Date: 2025-09-28 19:39:59.073227

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '777a974b47b4'
down_revision = '978bd79d7643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('APPLICATION', 'AUTO_APPROVAL', 'INTERNAL_ASSIGNMENT', 'CREATOR', name='joinmethod').create(op.get_bind())
    sa.Enum('ACTIVE', 'COMPLETED', 'LEFT', 'REMOVED', name='questmemberstatus').create(op.get_bind())
    sa.Enum('CREATOR', 'MEMBER', 'MODERATOR', name='questmemberrole').create(op.get_bind())
    op.create_table('quest_member',
    sa.Column('role', postgresql.ENUM('CREATOR', 'MEMBER', 'MODERATOR', name='questmemberrole', create_type=False), server_default='MEMBER', nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETED', 'LEFT', 'REMOVED', name='questmemberstatus', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('join_method', postgresql.ENUM('APPLICATION', 'AUTO_APPROVAL', 'INTERNAL_ASSIGNMENT', 'CREATOR', name='joinmethod', create_type=False), server_default='APPLICATION', nullable=False),
    sa.Column('assignment_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('source_application_id', sa.Uuid(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_application_id'], ['questapplication.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'user_id', name='uq_quest_member_quest_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_member')
    sa.Enum('CREATOR', 'MEMBER', 'MODERATOR', name='questmemberrole').drop(op.get_bind())
    sa.Enum('ACTIVE', 'COMPLETED', 'LEFT', 'REMOVED', name='questmemberstatus').drop(op.get_bind())
    sa.Enum('APPLICATION', 'AUTO_APPROVAL', 'INTERNAL_ASSIGNMENT', 'CREATOR', name='joinmethod').drop(op.get_bind())
    # ### end Alembic commands ###
