"""Remove owner from Item

Revision ID: 8e42be3d8405
Revises: 5d18dbc8c7e9
Create Date: 2025-08-31 20:03:33.999208

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8e42be3d8405'
down_revision = '5d18dbc8c7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
