"""Added new tables (tags, requests, chats, chat_messages, join tables) Rename some tables and added new fields

Revision ID: a9c6b78075cf
Revises: 54b34b5edd7a
Create Date: 2025-08-29 22:25:11.002007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9c6b78075cf'
down_revision = '54b34b5edd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('last_read_time', sa.DateTime(), nullable=True),
    sa.Column('notification_setting', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='check_chat_role'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_users_chat_id'), 'chats_users', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chats_users_id'), 'chats_users', ['id'], unique=False)
    op.create_index(op.f('ix_chats_users_user_id'), 'chats_users', ['user_id'], unique=False)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='check_request_role'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_users_id'), 'requests_users', ['id'], unique=False)
    op.create_index(op.f('ix_requests_users_request_id'), 'requests_users', ['request_id'], unique=False)
    op.create_index(op.f('ix_requests_users_user_id'), 'requests_users', ['user_id'], unique=False)
    op.create_table('tags_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_requests_id'), 'tags_requests', ['id'], unique=False)
    op.create_index(op.f('ix_tags_requests_request_id'), 'tags_requests', ['request_id'], unique=False)
    op.create_index(op.f('ix_tags_requests_tag_id'), 'tags_requests', ['tag_id'], unique=False)
    op.drop_index('ix_request_join_id', table_name='request_join')
    op.drop_index('ix_request_join_request_id', table_name='request_join')
    op.drop_index('ix_request_join_user_id', table_name='request_join')
    op.drop_table('request_join')
    op.drop_index('ix_chat_join_chat_id', table_name='chat_join')
    op.drop_index('ix_chat_join_id', table_name='chat_join')
    op.drop_index('ix_chat_join_user_id', table_name='chat_join')
    op.drop_table('chat_join')
    op.drop_index('ix_tag_join_id', table_name='tag_join')
    op.drop_index('ix_tag_join_request_id', table_name='tag_join')
    op.drop_index('ix_tag_join_tag_id', table_name='tag_join')
    op.drop_table('tag_join')
    op.add_column('chat_messages', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('chat_messages', 'status',
               existing_type=postgresql.ENUM('visible', 'edited', 'deleted', name='messagestatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('chat_messages', 'description')
    op.add_column('users', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.add_column('chat_messages', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('chat_messages', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('visible', 'edited', 'deleted', name='messagestatus'),
               existing_nullable=False)
    op.drop_column('chat_messages', 'text')
    op.create_table('tag_join',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='tag_join_request_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='tag_join_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tag_join_pkey')
    )
    op.create_index('ix_tag_join_tag_id', 'tag_join', ['tag_id'], unique=False)
    op.create_index('ix_tag_join_request_id', 'tag_join', ['request_id'], unique=False)
    op.create_index('ix_tag_join_id', 'tag_join', ['id'], unique=False)
    op.create_table('chat_join',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('owner', 'admin', 'member', name='chatrole'), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notification_setting', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='chat_join_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_join_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_join_pkey')
    )
    op.create_index('ix_chat_join_user_id', 'chat_join', ['user_id'], unique=False)
    op.create_index('ix_chat_join_id', 'chat_join', ['id'], unique=False)
    op.create_index('ix_chat_join_chat_id', 'chat_join', ['chat_id'], unique=False)
    op.create_table('request_join',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('owner', 'collaborator', 'viewer', name='requestrole'), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notification_setting', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='request_join_request_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='request_join_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='request_join_pkey')
    )
    op.create_index('ix_request_join_user_id', 'request_join', ['user_id'], unique=False)
    op.create_index('ix_request_join_request_id', 'request_join', ['request_id'], unique=False)
    op.create_index('ix_request_join_id', 'request_join', ['id'], unique=False)
    op.drop_index(op.f('ix_tags_requests_tag_id'), table_name='tags_requests')
    op.drop_index(op.f('ix_tags_requests_request_id'), table_name='tags_requests')
    op.drop_index(op.f('ix_tags_requests_id'), table_name='tags_requests')
    op.drop_table('tags_requests')
    op.drop_index(op.f('ix_requests_users_user_id'), table_name='requests_users')
    op.drop_index(op.f('ix_requests_users_request_id'), table_name='requests_users')
    op.drop_index(op.f('ix_requests_users_id'), table_name='requests_users')
    op.drop_table('requests_users')
    op.drop_table('item')
    op.drop_index(op.f('ix_chats_users_user_id'), table_name='chats_users')
    op.drop_index(op.f('ix_chats_users_id'), table_name='chats_users')
    op.drop_index(op.f('ix_chats_users_chat_id'), table_name='chats_users')
    op.drop_table('chats_users')
    # ### end Alembic commands ###
