"""Remove import __future__ from annotations and added quotes to the necessary models

Revision ID: f141eba18e94
Revises: b2e7a6491999
Create Date: 2025-08-31 19:57:51.086817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f141eba18e94'
down_revision = 'b2e7a6491999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
