"""add relevant_skills, created_at, and updated_at fields to quest applications

Revision ID: f32093191d49
Revises: eebccc4dd9b2
Create Date: 2025-09-14 23:06:52.938709

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f32093191d49'
down_revision = 'eebccc4dd9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questapplication', sa.Column('relevant_skills', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('questapplication', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('questapplication', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))

    # Initialize created_at and updated_at with existing applied_at values
    op.execute("""
        UPDATE questapplication
        SET created_at = applied_at, updated_at = applied_at
        WHERE created_at IS NULL OR updated_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questapplication', 'updated_at')
    op.drop_column('questapplication', 'created_at')
    op.drop_column('questapplication', 'relevant_skills')
    # ### end Alembic commands ###
