/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutQuestsRouteImport } from './routes/_layout/quests'
import { Route as LayoutMyQuestsRouteImport } from './routes/_layout/my-quests'
import { Route as LayoutMyApplicationsRouteImport } from './routes/_layout/my-applications'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutQuestsIndexRouteImport } from './routes/_layout/quests.index'
import { Route as LayoutQuestsCreateRouteImport } from './routes/_layout/quests.create'
import { Route as LayoutQuestsQuestIdRouteImport } from './routes/_layout/quests.$questId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestsRoute = LayoutQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyQuestsRoute = LayoutMyQuestsRouteImport.update({
  id: '/my-quests',
  path: '/my-quests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyApplicationsRoute = LayoutMyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestsIndexRoute = LayoutQuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutQuestsRoute,
} as any)
const LayoutQuestsCreateRoute = LayoutQuestsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutQuestsRoute,
} as any)
const LayoutQuestsQuestIdRoute = LayoutQuestsQuestIdRouteImport.update({
  id: '/$questId',
  path: '/$questId',
  getParentRoute: () => LayoutQuestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home': typeof LayoutHomeRoute
  '/my-applications': typeof LayoutMyApplicationsRoute
  '/my-quests': typeof LayoutMyQuestsRoute
  '/quests': typeof LayoutQuestsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/quests/$questId': typeof LayoutQuestsQuestIdRoute
  '/quests/create': typeof LayoutQuestsCreateRoute
  '/quests/': typeof LayoutQuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home': typeof LayoutHomeRoute
  '/my-applications': typeof LayoutMyApplicationsRoute
  '/my-quests': typeof LayoutMyQuestsRoute
  '/settings': typeof LayoutSettingsRoute
  '/quests/$questId': typeof LayoutQuestsQuestIdRoute
  '/quests/create': typeof LayoutQuestsCreateRoute
  '/quests': typeof LayoutQuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/my-applications': typeof LayoutMyApplicationsRoute
  '/_layout/my-quests': typeof LayoutMyQuestsRoute
  '/_layout/quests': typeof LayoutQuestsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/quests/$questId': typeof LayoutQuestsQuestIdRoute
  '/_layout/quests/create': typeof LayoutQuestsCreateRoute
  '/_layout/quests/': typeof LayoutQuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/home'
    | '/my-applications'
    | '/my-quests'
    | '/quests'
    | '/settings'
    | '/quests/$questId'
    | '/quests/create'
    | '/quests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/home'
    | '/my-applications'
    | '/my-quests'
    | '/settings'
    | '/quests/$questId'
    | '/quests/create'
    | '/quests'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/home'
    | '/_layout/my-applications'
    | '/_layout/my-quests'
    | '/_layout/quests'
    | '/_layout/settings'
    | '/_layout/quests/$questId'
    | '/_layout/quests/create'
    | '/_layout/quests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quests': {
      id: '/_layout/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof LayoutQuestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-quests': {
      id: '/_layout/my-quests'
      path: '/my-quests'
      fullPath: '/my-quests'
      preLoaderRoute: typeof LayoutMyQuestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-applications': {
      id: '/_layout/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof LayoutMyApplicationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quests/': {
      id: '/_layout/quests/'
      path: '/'
      fullPath: '/quests/'
      preLoaderRoute: typeof LayoutQuestsIndexRouteImport
      parentRoute: typeof LayoutQuestsRoute
    }
    '/_layout/quests/create': {
      id: '/_layout/quests/create'
      path: '/create'
      fullPath: '/quests/create'
      preLoaderRoute: typeof LayoutQuestsCreateRouteImport
      parentRoute: typeof LayoutQuestsRoute
    }
    '/_layout/quests/$questId': {
      id: '/_layout/quests/$questId'
      path: '/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof LayoutQuestsQuestIdRouteImport
      parentRoute: typeof LayoutQuestsRoute
    }
  }
}

interface LayoutQuestsRouteChildren {
  LayoutQuestsQuestIdRoute: typeof LayoutQuestsQuestIdRoute
  LayoutQuestsCreateRoute: typeof LayoutQuestsCreateRoute
  LayoutQuestsIndexRoute: typeof LayoutQuestsIndexRoute
}

const LayoutQuestsRouteChildren: LayoutQuestsRouteChildren = {
  LayoutQuestsQuestIdRoute: LayoutQuestsQuestIdRoute,
  LayoutQuestsCreateRoute: LayoutQuestsCreateRoute,
  LayoutQuestsIndexRoute: LayoutQuestsIndexRoute,
}

const LayoutQuestsRouteWithChildren = LayoutQuestsRoute._addFileChildren(
  LayoutQuestsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutMyApplicationsRoute: typeof LayoutMyApplicationsRoute
  LayoutMyQuestsRoute: typeof LayoutMyQuestsRoute
  LayoutQuestsRoute: typeof LayoutQuestsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutMyApplicationsRoute: LayoutMyApplicationsRoute,
  LayoutMyQuestsRoute: LayoutMyQuestsRoute,
  LayoutQuestsRoute: LayoutQuestsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
